name: salem
description: SALEM - A text-based, visual novel 2d game engine.
version: 0.0.1
homepage: https://github.com/SmallDreams/Engine
repository: https://github.com/SmallDreams/Engine

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # core
  shared_preferences: ^2.0.6
  
  # audio
  dart_vlc: ^0.0.7
  audioplayers: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true