name: salem
description: SALEM - A cross-platform visual novel game engine, developed in Flutter.
version: 0.0.3
homepage: https://github.com/SmallDreams/Engine
repository: https://github.com/SmallDreams/Engine

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # core
  universal_platform: ">=1.0.0+1 <2.0.0"
  shared_preferences: ">=2.0.6 <3.0.0"
  
  # audio
  dart_vlc:
    git:
      url: git://github.com/alexmercerind/dart_vlc.git
      ref: 83db3e11a871cdb20a66d38ced53f13953120ae7
  audioplayers: ">=0.19.1 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
 # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true